# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glad_config = debug
  CometaFramework_config = debug

else ifeq ($(config),release)
  glad_config = release
  CometaFramework_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glad CometaFramework

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C vendor/glad -f Makefile config=$(glad_config)
endif

CometaFramework: glad
ifneq (,$(CometaFramework_config))
	@echo "==== Building CometaFramework ($(CometaFramework_config)) ===="
	@${MAKE} --no-print-directory -C . -f CometaFramework.make config=$(CometaFramework_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C . -f CometaFramework.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glad"
	@echo "   CometaFramework"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"