#ifndef COMETA_EVENT_TYPE_H
#define COMETA_EVENT_TYPE_H

enum EventType{
    NONE = 0,
    WINDOW_CLOSE,
    WINDOW_RESIZE,
    COMETA_KEY_PRESS_EVENT,
    COMETA_KEY_RELEASE_EVENT,
    COMETA_MOUSE_MOVE_EVENT,
    COMETA_MOUSE_SCROLL_EVENT,
    COMETA_MOUSE_BUTTON_PRESS_EVENT,
    COMETA_MOUSE_BUTTON_RELEASE_EVENT,
    TEST = 256
}; 



#endif